export const ajaydsInfo = [
	{
		id: "home-identity",
		text: "AjayDS is an AI development agency founded and run by Ajay Dhanraj Sonar. We specialize in building AI-powered web apps, workflow automations, and data pipelines — end to end, from idea to deployment. With 3 years of focused experience in AI and full-stack development, we work with founders and businesses who want to build serious AI products, not just experiment with them.",
		section: "home",
		url: "/",
	},
	{
		id: "home-positioning",
		text: "We're not a typical freelancer-for-hire setup. AjayDS operates like a focused AI product studio — we take ownership of what we build, we think in systems, and we care about outcomes, not just deliverables. Every engagement is scoped clearly, built transparently, and handed off with everything you need to own it fully.",
		section: "home",
		url: "/",
	},
	{
		id: "home-what-we-do",
		text: "We help businesses build three types of things: AI-powered web applications and MVPs, intelligent workflow automations, and data pipelines with dashboards. Whether you're a solo founder with a product idea or a growing business drowning in manual processes — we build the AI infrastructure that moves you forward.",
		section: "home",
		url: "/",
	},
	{
		id: "home-techstack",
		text: "Our core tech stack is Next.js, React, Node.js, and Python. We integrate AI using OpenAI and Anthropic Claude APIs. For automation we use Python and n8n. For data engineering we use Scrapy, Playwright, and Pandas. We deploy on Vercel, Railway, and custom infrastructure depending on what makes sense for your project.",
		section: "home",
		url: "/",
	},
	{
		id: "home-contact",
		text: "You can reach us directly at ajay@ajayds.com or on WhatsApp at +91 8788221865. Find us on LinkedIn at linkedin.com/in/ajaydsonar, on X at x.com/ajaydsonarr, and on GitHub at github.com/ajaydsonar. Our website is ajayds.com.",
		section: "home",
		url: "/",
	},
	{
		id: "services-overview",
		text: "We offer three core services at AjayDS: AI-Powered Web Apps & MVPs, AI Workflow Automation, and AI Data Pipelines & Dashboards. Each service is scoped and delivered end to end — we don't hand you a half-built product. Pricing is project-based and discussed after an initial discovery call.",
		section: "services",
		url: "/services",
	},
	{
		id: "service-webapps-overview",
		text: "Our AI-Powered Web Apps & MVPs service is built for founders and startups who want to ship a real product fast. We handle the full stack — Next.js frontend, Python or Node.js backend, database, auth, billing, and AI features — so you don't have to coordinate between five different contractors. The tagline is: Ship your vision, not just your code.",
		section: "services",
		url: "/services/ai-webapps-mvp",
	},
	{
		id: "service-webapps-deliverables",
		text: "What's included in the AI Web Apps & MVPs service: responsive React or Next.js frontend, AI features powered by OpenAI or Claude APIs, backend API in Node.js or Python FastAPI, database design and setup in PostgreSQL or MongoDB, user authentication, billing integration, user management, and full deployment on Vercel, Railway, or your own infrastructure.",
		section: "services",
		url: "/services/ai-webapps-mvp",
	},
	{
		id: "service-webapps-process",
		text: "How we work on AI Web Apps & MVPs: We start with a discovery call to understand your idea, your users, and what AI capabilities actually make sense. Then we send a clear written scope — deliverables, integration points, timeline, and price, no vague estimates. We build in 1-week sprints with a working demo each week so you see real progress. At the end we deploy, hand over the source code, documentation, and full access to everything.",
		section: "services",
		url: "/services/ai-webapps-mvp",
	},
	{
		id: "service-automation-overview",
		text: "Our AI Workflow Automation service is for businesses where time is being lost to repetitive manual work. If your team is copy-pasting between tools, manually following up with leads, or running the same process every day — we automate it using Python and n8n, usually with a working version live within days. The tagline is: Stop doing the work your software should be doing.",
		section: "services",
		url: "/services/ai-workflow-automation",
	},
	{
		id: "service-automation-deliverables",
		text: "What's included in the AI Workflow Automation service: custom Python automation scripts, n8n workflow orchestration, API integrations with CRMs, email platforms, Slack, and WhatsApp, AI-powered decision making inside workflows, scheduled and webhook-triggered automation, and error monitoring with alerting so issues surface before your customers see them.",
		section: "services",
		url: "/services/ai-workflow-automation",
	},
	{
		id: "service-automation-process",
		text: "How we work on AI Workflow Automation: You walk us through what you do manually. We map every step that can be automated and every edge case that can't. Most automations have a working version within 2 to 3 days. We then run it alongside your existing process on real data before it ever replaces anything. Once proven, we deploy it on a schedule with full error alerting.",
		section: "services",
		url: "/services/ai-workflow-automation",
	},
	{
		id: "service-datapipelines-overview",
		text: "Our AI Data Pipelines & Dashboards service turns raw, scattered data into something your business can actually use. We build pipelines that scrape, clean, and transform data from any source, then surface it in a focused dashboard with AI-powered insights. Whether it's competitor pricing, market intel, or your own internal metrics — we build the infrastructure to make it visible and actionable. The tagline is: Your next big move is already in your data.",
		section: "services",
		url: "/services/ai-data-pipelines",
	},
	{
		id: "service-datapipelines-deliverables",
		text: "What's included in the AI Data Pipelines & Dashboards service: web scraping and data extraction using Scrapy and Playwright, ETL pipelines built in Python and Pandas, real-time or scheduled data processing, interactive dashboards in Next.js with Recharts, AI-powered anomaly detection and insights, and automated reporting with threshold-based alerts.",
		section: "services",
		url: "/services/ai-data-pipelines",
	},
	{
		id: "service-datapipelines-process",
		text: "How we work on AI Data Pipelines & Dashboards: We start by auditing where your data lives and what you're doing with it manually. We build the scraping and transformation layer first — you see raw data flowing within the first week. Then we build a focused dashboard around the metrics that help you make decisions, not a wall of charts. Finally, everything runs on a schedule with auto-updating dashboards and alerts when something needs attention.",
		section: "services",
		url: "/services/ai-data-pipelines",
	},
	{
		id: "blog-upcoming",
		text: "The AjayDS blog is coming soon. It will cover practical topics around building with AI — including tutorials, breakdowns of real projects, and thoughts on AI tooling, automation patterns, and building AI products that actually work in production.",
		section: "blog",
		url: "/blog",
	},
	{
		id: "faq-who-is-this-for",
		text: "AjayDS works best with solo founders validating a product idea, early-stage startups who need to move fast without a full engineering team, and growing businesses with repetitive manual workflows or untapped data. We're a good fit if you want a technical partner who takes ownership, not just someone who executes a ticket.",
		section: "home",
		url: "/",
	},
	{
		id: "faq-pricing",
		text: "We work on a project basis, not hourly. Every project is scoped individually based on complexity, timeline, and what's actually needed. We don't publish fixed rates because no two projects are identical — but every engagement starts with a clear written scope that includes deliverables and price before any work begins. To get a quote, reach out at ajay@ajayds.com or WhatsApp +91 8788221865.",
		section: "home",
		url: "/",
	},
	{
		id: "faq-get-started",
		text: "The best way to start a project with AjayDS is to send a short message to ajay@ajayds.com or WhatsApp +91 8788221865 describing what you're trying to build or automate. We'll schedule a free discovery call, understand the scope, and send back a clear proposal. No commitment required for the first call.",
		section: "home",
		url: "/",
	},
];
