/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seoTitle?: string;
  description?: string;
  excerpt?: string;
  publishedAt?: string;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AuthorReference
  | CategoryReference
  | SanityImageAssetReference
  | Post
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../ajayds-web/src/lib/sanity/queries.ts
// Variable: POSTS_QUERY
// Query: *[    _type == "post" &&    defined(slug.current) &&    publishedAt <= now()  ] | order(publishedAt desc) {    _id,    title,    "slug": slug.current,    description,    excerpt,    publishedAt,    _updatedAt,    coverImage {      _type,      alt,      caption,      "url": asset->url,      "assetId": asset->_id,      "dimensions": asset->metadata.dimensions {        width,        height,        aspectRatio      },      crop {        top,        bottom,        left,        right      },      hotspot {        x,        y,        height,        width      }    },    author->{      name,      "slug": slug.current    },    categories[]->{      title,      "slug": slug.current    }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  coverImage: {
    _type: "image";
    alt: string | null;
    caption: string | null;
    url: string | null;
    assetId: string | null;
    dimensions: {
      width: number | null;
      height: number | null;
      aspectRatio: number | null;
    } | null;
    crop: {
      top: number | null;
      bottom: number | null;
      left: number | null;
      right: number | null;
    } | null;
    hotspot: {
      x: number | null;
      y: number | null;
      height: number | null;
      width: number | null;
    } | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: ../ajayds-web/src/lib/sanity/queries.ts
// Variable: POST_QUERY
// Query: *[    _type == "post" &&    slug.current == $slug &&    publishedAt <= now()  ][0] {    _id,    _updatedAt,    title,    "slug": slug.current,    seoTitle,    description,    excerpt,    publishedAt,    "modifiedAt": coalesce(_updatedAt, publishedAt),    coverImage {      _type,      alt,      caption,      "url": asset->url,      "assetId": asset->_id,      "dimensions": asset->metadata.dimensions {        width,        height,        aspectRatio      },      crop {        top,        bottom,        left,        right      },      hotspot {        x,        y,        height,        width      }    },    author->{      name,      "slug": slug.current,      bio    },    categories[]->{      title,      "slug": slug.current    },    body[] {      _type == "block" => {        _key,        _type,        style,        listItem,        level,        children[] {          _key,          _type,          text,          marks        },        markDefs[] {          _key,          _type,          href,          openInNewTab        }      },      _type == "image" => {        _key,        _type,        alt,        caption,        "url": asset->url,        "assetId": asset->_id,        "dimensions": asset->metadata.dimensions {          width,          height,          aspectRatio        },        crop {          top,          bottom,          left,          right        },        hotspot {          x,          y,          height,          width        }      }    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  seoTitle: string | null;
  description: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  modifiedAt: string;
  coverImage: {
    _type: "image";
    alt: string | null;
    caption: string | null;
    url: string | null;
    assetId: string | null;
    dimensions: {
      width: number | null;
      height: number | null;
      aspectRatio: number | null;
    } | null;
    crop: {
      top: number | null;
      bottom: number | null;
      left: number | null;
      right: number | null;
    } | null;
    hotspot: {
      x: number | null;
      y: number | null;
      height: number | null;
      width: number | null;
    } | null;
  } | null;
  author: {
    name: string | null;
    slug: string | null;
    bio: string | null;
  } | null;
  categories: Array<{
    title: string | null;
    slug: string | null;
  }> | null;
  body: Array<
    | {
        _key: string;
        _type: "block";
        style: "blockquote" | "h2" | "h3" | "normal" | null;
        listItem: "bullet" | "number" | null;
        level: number | null;
        children: Array<{
          _key: string;
          _type: "span";
          text: string | null;
          marks: Array<string> | null;
        }> | null;
        markDefs: Array<{
          _key: string;
          _type: "link";
          href: string | null;
          openInNewTab: boolean | null;
        }> | null;
      }
    | {
        _key: string;
        _type: "image";
        alt: string | null;
        caption: string | null;
        url: string | null;
        assetId: string | null;
        dimensions: {
          width: number | null;
          height: number | null;
          aspectRatio: number | null;
        } | null;
        crop: {
          top: number | null;
          bottom: number | null;
          left: number | null;
          right: number | null;
        } | null;
        hotspot: {
          x: number | null;
          y: number | null;
          height: number | null;
          width: number | null;
        } | null;
      }
  > | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n    _type == "post" &&\n    defined(slug.current) &&\n    publishedAt <= now()\n  ] | order(publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    excerpt,\n    publishedAt,\n    _updatedAt,\n\n    coverImage {\n      _type,\n      alt,\n      caption,\n      "url": asset->url,\n      "assetId": asset->_id,\n      "dimensions": asset->metadata.dimensions {\n        width,\n        height,\n        aspectRatio\n      },\n      crop {\n        top,\n        bottom,\n        left,\n        right\n      },\n      hotspot {\n        x,\n        y,\n        height,\n        width\n      }\n    },\n\n    author->{\n      name,\n      "slug": slug.current\n    },\n\n    categories[]->{\n      title,\n      "slug": slug.current\n    }\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    slug.current == $slug &&\n    publishedAt <= now()\n  ][0] {\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    seoTitle,\n    description,\n    excerpt,\n    publishedAt,\n    "modifiedAt": coalesce(_updatedAt, publishedAt),\n\n    coverImage {\n      _type,\n      alt,\n      caption,\n      "url": asset->url,\n      "assetId": asset->_id,\n      "dimensions": asset->metadata.dimensions {\n        width,\n        height,\n        aspectRatio\n      },\n      crop {\n        top,\n        bottom,\n        left,\n        right\n      },\n      hotspot {\n        x,\n        y,\n        height,\n        width\n      }\n    },\n\n    author->{\n      name,\n      "slug": slug.current,\n      bio\n    },\n\n    categories[]->{\n      title,\n      "slug": slug.current\n    },\n\n    body[] {\n      _type == "block" => {\n        _key,\n        _type,\n        style,\n        listItem,\n        level,\n        children[] {\n          _key,\n          _type,\n          text,\n          marks\n        },\n        markDefs[] {\n          _key,\n          _type,\n          href,\n          openInNewTab\n        }\n      },\n\n      _type == "image" => {\n        _key,\n        _type,\n        alt,\n        caption,\n        "url": asset->url,\n        "assetId": asset->_id,\n        "dimensions": asset->metadata.dimensions {\n          width,\n          height,\n          aspectRatio\n        },\n        crop {\n          top,\n          bottom,\n          left,\n          right\n        },\n        hotspot {\n          x,\n          y,\n          height,\n          width\n        }\n      }\n    }\n  }\n': POST_QUERY_RESULT;
  }
}
